<?xml version="1.0"?>
<!DOCTYPE Report[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="HP Service Test" productVer="11.50" os="Windows XP" host="ADMIN-FA4389E57"><DocLocation><![CDATA[C:\AT_Demo\API]]></DocLocation></General>
<Doc rID="T1" productName="HP Service Test" updated="true">
<DName><![CDATA[API]]></DName>
<Res><![CDATA[Result5]]></Res>
<Step rID="T2">
<Obj plainTxt="False"><![CDATA[Start]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:56]]></Time>
<TimeTick>1734648596</TimeTick>
<NodeArgs eType="Replay" icon="10001" nRep="4" StepFlowItemKey="StartActivity1">
<Disp><![CDATA[Start]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step0.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T3">
<Obj plainTxt="False"><![CDATA[Test Flow]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:56]]></Time>
<TimeTick>1734648596</TimeTick>
<Action rID="T4">
<AName><![CDATA[]]></AName>
<AIter rID="T5" iterID="1" isCountable="True">
<Step rID="T6">
<Obj plainTxt="False"><![CDATA[Condition5]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T7">
<Obj plainTxt="False"><![CDATA[Yes]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T8">
<Obj plainTxt="False"><![CDATA[CreateFlightOrder]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T9">
<Obj plainTxt="False"><![CDATA[Checkpoints]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<NodeArgs eType="Replay" icon="2" nRep="11" status="Passed" StepFlowItemKey="StServiceCallActivity4">
<Disp><![CDATA[Checkpoints]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="1" />
</DataMapping>
<NodeArgs eType="Replay" icon="10004" nRep="10" status="Passed" StepFlowItemKey="StServiceCallActivity4">
<Disp><![CDATA[CreateFlightOrder]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step2.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="1" />
</DataMapping>
<NodeArgs eType="Replay" icon="2" nRep="9" status="Passed" StepFlowItemKey="IfElseBranch6">
<Disp><![CDATA[Yes]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step3.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10003" nRep="8" status="Passed" StepFlowItemKey="IfElse5">
<Disp><![CDATA[Condition5]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step4.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="4" nRep="7" status="Passed" StepFlowItemKey="Loop2">
<Disp><![CDATA[Iteration 1]]></Disp>
<BtmPane vType="HTML" ShowDifference="False">
<Path><![CDATA[Data\Step5.xml]]></Path>
</BtmPane>
</NodeArgs>
</AIter>
<Summary sTime="12/19/2024 - 17:49:57" eTime="12/19/2024 - 17:49:57" passed="1" failed="0" warnings="0"></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed">
<Disp><![CDATA[ Summary]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step5.xml]]></Path>
</BtmPane>
</NodeArgs>
</Action>
<Action rID="T12">
<AName><![CDATA[]]></AName>
<AIter rID="T13" iterID="2" isCountable="True">
<Step rID="T14">
<Obj plainTxt="False"><![CDATA[Condition5]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T15">
<Obj plainTxt="False"><![CDATA[No]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T16">
<Obj plainTxt="False"><![CDATA[CreateFlightOrder]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T17">
<Obj plainTxt="False"><![CDATA[Checkpoints]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<NodeArgs eType="Replay" icon="2" nRep="23" status="Passed" StepFlowItemKey="StServiceCallActivity8">
<Disp><![CDATA[Checkpoints]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step6.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="2" />
</DataMapping>
<NodeArgs eType="Replay" icon="10004" nRep="22" status="Passed" StepFlowItemKey="StServiceCallActivity8">
<Disp><![CDATA[CreateFlightOrder]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step7.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="2" />
</DataMapping>
<NodeArgs eType="Replay" icon="2" nRep="21" status="Passed" StepFlowItemKey="IfElseBranch7">
<Disp><![CDATA[No]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step8.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10003" nRep="20" status="Passed" StepFlowItemKey="IfElse5">
<Disp><![CDATA[Condition5]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step9.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="4" nRep="19" status="Passed" StepFlowItemKey="Loop2">
<Disp><![CDATA[Iteration 2]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step10.xml]]></Path>
</BtmPane>
</NodeArgs>
</AIter>
<Summary sTime="12/19/2024 - 17:49:57" eTime="12/19/2024 - 17:49:57" passed="1" failed="0" warnings="0"></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="18" status="Passed">
<Disp><![CDATA[ Summary]]></Disp>
<BtmPane vType="HTML" ShowDifference="False">
<Path><![CDATA[Data\Step10.xml]]></Path>
</BtmPane>
</NodeArgs>
</Action>
<Action rID="T20">
<AName><![CDATA[]]></AName>
<AIter rID="T21" iterID="3" isCountable="True">
<Step rID="T22">
<Obj plainTxt="False"><![CDATA[Condition5]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T23">
<Obj plainTxt="False"><![CDATA[No]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T24">
<Obj plainTxt="False"><![CDATA[CreateFlightOrder]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:57]]></Time>
<TimeTick>1734648597</TimeTick>
<Step rID="T25">
<Obj plainTxt="False"><![CDATA[Checkpoints]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<NodeArgs eType="Replay" icon="2" nRep="35" status="Passed" StepFlowItemKey="StServiceCallActivity8">
<Disp><![CDATA[Checkpoints]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step11.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="3" />
</DataMapping>
<NodeArgs eType="Replay" icon="10004" nRep="34" status="Passed" StepFlowItemKey="StServiceCallActivity8">
<Disp><![CDATA[CreateFlightOrder]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step12.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="3" />
</DataMapping>
<NodeArgs eType="Replay" icon="2" nRep="33" status="Passed" StepFlowItemKey="IfElseBranch7">
<Disp><![CDATA[No]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step13.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10003" nRep="32" status="Passed" StepFlowItemKey="IfElse5">
<Disp><![CDATA[Condition5]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step14.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="4" nRep="31" status="Passed" StepFlowItemKey="Loop2">
<Disp><![CDATA[Iteration 3]]></Disp>
<BtmPane vType="HTML" ShowDifference="False">
<Path><![CDATA[Data\Step15.xml]]></Path>
</BtmPane>
</NodeArgs>
</AIter>
<Summary sTime="12/19/2024 - 17:49:57" eTime="12/19/2024 - 17:49:58" passed="1" failed="0" warnings="0"></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="30" status="Passed">
<Disp><![CDATA[ Summary]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step15.xml]]></Path>
</BtmPane>
</NodeArgs>
</Action>
<Action rID="T28">
<AName><![CDATA[]]></AName>
<AIter rID="T29" iterID="4" isCountable="True">
<Step rID="T30">
<Obj plainTxt="False"><![CDATA[Condition5]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<Step rID="T31">
<Obj plainTxt="False"><![CDATA[No]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<Step rID="T32">
<Obj plainTxt="False"><![CDATA[CreateFlightOrder]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<Step rID="T33">
<Obj plainTxt="False"><![CDATA[Checkpoints]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<NodeArgs eType="Replay" icon="2" nRep="47" status="Passed" StepFlowItemKey="StServiceCallActivity8">
<Disp><![CDATA[Checkpoints]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step16.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="4" />
</DataMapping>
<NodeArgs eType="Replay" icon="10004" nRep="46" status="Passed" StepFlowItemKey="StServiceCallActivity8">
<Disp><![CDATA[CreateFlightOrder]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step17.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<DataMapping>
<DataMappedItem dsName="data!Sheet1" rowId="4" />
</DataMapping>
<NodeArgs eType="Replay" icon="2" nRep="45" status="Passed" StepFlowItemKey="IfElseBranch7">
<Disp><![CDATA[No]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step18.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10003" nRep="44" status="Passed" StepFlowItemKey="IfElse5">
<Disp><![CDATA[Condition5]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step19.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="4" nRep="43" status="Passed" StepFlowItemKey="Loop2">
<Disp><![CDATA[Iteration 4]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step20.xml]]></Path>
</BtmPane>
</NodeArgs>
</AIter>
<Summary sTime="12/19/2024 - 17:49:58" eTime="12/19/2024 - 17:49:58" passed="1" failed="0" warnings="0"></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="42" status="Passed">
<Disp><![CDATA[ Summary]]></Disp>
<BtmPane vType="HTML" ShowDifference="False">
<Path><![CDATA[Data\Step20.xml]]></Path>
</BtmPane>
</NodeArgs>
</Action>
<NodeArgs eType="Replay" icon="10002" nRep="5" status="Passed" StepFlowItemKey="Loop2">
<Disp><![CDATA[Test Flow]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step21.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False"><![CDATA[End]]></Obj>
<Details plainTxt="False"><![CDATA[]]></Details>
<Time><![CDATA[12/19/2024 - 17:49:58]]></Time>
<TimeTick>1734648598</TimeTick>
<NodeArgs eType="Replay" icon="10005" nRep="54" StepFlowItemKey="EndActivity3">
<Disp><![CDATA[End]]></Disp>
<BtmPane vType="HTML">
<Path><![CDATA[Data\Step22.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="12/19/2024 - 17:49:56" eTime="12/19/2024 - 17:49:58" passed="4" failed="0" warnings="0"></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed">
<Disp><![CDATA[Test API Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>